"""Referted back because of errors

Revision ID: 160bf0795ed8
Revises: 57a3c760b027
Create Date: 2024-10-31 14:24:42.562968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '160bf0795ed8'
down_revision = '57a3c760b027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_component')
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_constraint('component_ibfk_2', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('component_ibfk_2', 'component', ['parent_id'], ['id'])

    op.create_table('sub_component',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('component_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sub_component_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], name='sub_component_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
